version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: mvn clean install -DskipTests
  test:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: mvn clean test

workflows:
  build_and_test:
    jobs:
      - build
      - test